request httpServletRequest;
response httpServletResponce;
page currentJsp
pageContext pageContext;
session HttpSession;
config servletConfig;
application ServletContext;
out jspWriter;
exception throwable 